# Generated by Django 4.2.14 on 2024-07-28 22:42

import db_models.gearstore
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminPassword',
            fields=[
                ('id', models.TextField(default=db_models.gearstore.id_generator, max_length=6, primary_key=True, serialize=False)),
                ('password', models.CharField(default='password123', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.TextField(default=db_models.gearstore.id_generator, max_length=6, primary_key=True, serialize=False)),
                ('purpose', models.TextField(choices=[('Affiliated', 'Affiliated'), ('Personal', 'Personal')], default='Personal')),
                ('dateBorrowed', models.DateField(auto_now_add=True)),
                ('dateToReturn', models.DateField(default=db_models.gearstore.return_date_time)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Requested', 'Requested'), ('Accepted', 'Accepted'), ('Denied', 'Denied'), ('Returned', 'Returned'), ('Unreturned', 'Unreturned')], default='Requested', max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('name', models.CharField(max_length=128, unique=True)),
                ('description', models.CharField(max_length=128)),
                ('dateAdded', models.DateField(auto_now_add=True)),
                ('picture', models.ImageField(default='gearstore/category_images/default.png', upload_to='gearstore/category_images')),
                ('slug', models.SlugField(primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='PageContents',
            fields=[
                ('background_image', models.ImageField(default='gearstore/site_images/default_background.jpg', upload_to='gearstore/site_images')),
                ('logo_image', models.ImageField(default='gearstore/site_images/default_logo.png', upload_to='gearstore/site_images')),
                ('icon_image', models.ImageField(default='gearstore/site_images/default_icon.png', upload_to='gearstore/site_images')),
                ('home_contents', models.TextField(default='')),
                ('about_contents', models.TextField(default='')),
                ('contact_contents', models.TextField(default='')),
                ('contact', models.CharField(default='07123 456 789', max_length=128)),
                ('contact_option', models.CharField(choices=[('logo-whatsapp', 'WhatsApp'), ('call-outline', 'Phone Number'), ('mail-outline', 'Email')], default='call-outline', max_length=128)),
                ('title', models.TextField(default='Gear Store')),
                ('domain', models.URLField(default='')),
                ('auto_increment_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='SidebarLinks',
            fields=[
                ('link_text', models.TextField()),
                ('url', models.URLField()),
                ('id', models.TextField(default=db_models.gearstore.comment_id_generator, max_length=6, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('adminStatus', models.BooleanField(default=False)),
                ('first_name', models.CharField(default='Jane', max_length=30)),
                ('last_name', models.CharField(default='Doe', max_length=30)),
                ('picture', models.ImageField(default='gearstore/profile_images/default.jpeg', upload_to='gearstore/profile_images')),
            ],
        ),
        migrations.CreateModel(
            name='QR_Code',
            fields=[
                ('qr_code', models.ImageField(default='gearstore/qrcode_images/default_qrcode.png', upload_to='gearstore/qrcode_images')),
                ('domain', models.TextField(default='')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='gearstore_app.booking')),
            ],
        ),
        migrations.CreateModel(
            name='Gear',
            fields=[
                ('name', models.CharField(max_length=128)),
                ('deposit', models.TextField(default='Free', max_length=16)),
                ('description', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('In Service', 'In Service'), ('Out Of Service', 'Out Of Service')], default='In Service', max_length=16)),
                ('dateAdded', models.DateField(auto_now_add=True)),
                ('picture', models.ImageField(default='gearstore/gear_images/default.png', upload_to='gearstore/gear_images')),
                ('size', models.CharField(max_length=128)),
                ('slug', models.SlugField(primary_key=True, serialize=False, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gearstore_app.category')),
            ],
            options={
                'verbose_name_plural': 'Gear',
            },
        ),
        migrations.CreateModel(
            name='BookingComments',
            fields=[
                ('comment', models.TextField()),
                ('starred', models.BooleanField(default=False)),
                ('id', models.TextField(default=db_models.gearstore.comment_id_generator, max_length=6, primary_key=True, serialize=False)),
                ('dateAdded', models.DateField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gearstore_app.booking')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gearstore_app.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='gearItem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gearstore_app.gear'),
        ),
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gearstore_app.userprofile'),
        ),
    ]
